const verbs = [
    "abrir",
//    "#acostarse",
    "apagar",
    "aprender",
    "ayudar",
    "bajar",
    "buscar",
//    "#caerse",
    "cambiar",
    "caminar",
    "cerrar",
    "comer",
    "comprar",
    "conocer",
    "correr",
    "cortar",
    "creer",
    "cuidar",
    "dar",
    "decir",
    "dejar",
    "descansar",
//    "#despertarse",
//    "#divertirse",
//    "#domrirse",
    "dormir",
//    "#dormirse",
    "empezar",
    "encontrar",
    "ensenar",
    "entender",
    "escribir",
    "escuchar",
    "esperar",
    "estar",
    "estudiar",
    "gustar",
    "hablar",
    "hacer",
    "ir",
    "jugar",
//    "#lavarse",
    "leer",
//    "#levantarse",
    "limpiar",
//    "#llamarse",
    "llegar",
    "llevar",
    "mandar",
    "mirar",
    "morir",
    "nadar",
    "necesitar",
    "pagar",
    "pedir",
    "pensar",
    "poder",
    "poner",
    "preguntar",
    "prender",
    "prestar",
    "querer",
//    "#quitarse",
    "saber",
    "salir",
//    "#sentarse",
    "ser",
    "servir",
    "subir",
    "tener",
    "tomar",
    "trabajar",
    "traer",
    "tratar",
    "vender",
    "venir",
    "ver",
    "viajar",
    "virir",
    "volver"
]

module.exports = { verbs }