open: "abrir",
"go to bed": "acostarse",
turn off: "apagar",
learn: "aprender",
help: "ayudar",
bajar: "go down",
buscar: "search for",
caerse: "fall",
cambiar: "change",
caminar: "walk",
cerrar: "close",
comer: "eat",
comprar: "buy",
conocer: "know",
correr: "run",
cortar: "cut",
creer: "believe",
cuidar: "take care of",
dar: "give",
decir: "say",
dejar: "leave",
descansar: "rest",
despertarse: "wake up",
divertirse: "have fun",
dormirse: "fall asleep",
dormir: "sleep",
empezar: "start",
encontrar: "find",
enseñar: "teach",
entender: "understand",
escribir: "write",
escuchar: "listen",
esperar: "hope",
estar: "be #stem changer",
estudiar: "study",
gustar: "like",
hablar: "speak",
hacer: "do",
ir: "go #stem changer",
jugar: "play",
lavarse: "wash",
leer: "read",
levantarse: "get up",
limpiar: "clean",
llamarse: "be called",
llegar: "arrive",
llevar: "carry",
mandar: "order",
mirar: "watch",
morir: "die",
nadar: "swim",
necesitar: "need",
pagar: "pay",
pedir: "ask for",
pensar: "think",
poder: "be able to",
poner: "put",
preguntar: "ask",
prender: "turn on",
prestar: "lend",
querer: "want",
quitarse: "take off",
saber: "know",
salir: "go out",
sentarse: "sit",
servir: "serve",
subir: "go up",
tener: "have",
tomar: "drink",
trabajar: "work",
traer: "bring",
tratar: "try",
vender: "sell",
venir: "come",
ver: "see",
viajar: "travel",
vivir: "go",
volver: "return",